doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: dbname
                user: user
                password: password
                host: host
                driver: pdo_mysql
                server_version: '10.0.38-MariaDB'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App